baseURL = 'https://lesminimonstres.fr/'
#languageCode = 'fr-fr'
title = 'Les Mini Monstres'
theme = "hugo-theme-massively"
disableKinds = ["taxonomy", "taxonomyTerm", "section"]
defaultContentLanguage = 'fr'

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"
  # backgroundPath = "images/bg.jpg"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false
 
[languages]
[languages.en]
  languageName = "English"
  disabled = true
[languages.es]
  languageName = "Español"
  title = "Massively - Versión Español"
  disabled = true
[languages.fr]
  languageName = "Français"
  title = "Massively - Version Française"

